# Generated by Django 3.0 on 2020-01-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decision_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problems',
            options={'ordering': ['title'], 'verbose_name': 'Проблема', 'verbose_name_plural': 'Проблемы'},
        ),
        migrations.AlterModelOptions(
            name='selections',
            options={'ordering': ['title'], 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.RenameField(
            model_name='problems',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='selections',
            old_name='name',
            new_name='title',
        ),
    ]
