# Generated by Django 3.0 on 2020-01-07 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('relevant', models.BooleanField(verbose_name='Действует')),
                ('published', models.DateTimeField(auto_now=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Проблема',
                'verbose_name_plural': 'Проблемы',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('relevant', models.BooleanField(verbose_name='Действует')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('relevant', models.BooleanField(verbose_name='Действует')),
                ('published', models.DateTimeField(verbose_name='Опубликовано')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.Problems')),
            ],
            options={
                'verbose_name': 'Решение',
                'verbose_name_plural': 'Решения',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Processes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('relevant', models.BooleanField(verbose_name='Действует')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.Section')),
            ],
            options={
                'verbose_name': 'Процесс',
                'verbose_name_plural': 'Процессы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='problems',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.Processes'),
        ),
    ]
