# Generated by Django 3.0 on 2020-01-08 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('relevant', models.BooleanField(default=True, verbose_name='Действует')),
            ],
            options={
                'verbose_name': 'Область знаний',
                'verbose_name_plural': 'Области знаний',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='problems',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.Processes', verbose_name='Процесс'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='relevant',
            field=models.BooleanField(default=True, verbose_name='Действует'),
        ),
        migrations.AlterField(
            model_name='processes',
            name='relevant',
            field=models.BooleanField(default=True, verbose_name='Действует'),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.Problems', verbose_name='Проблема'),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='relevant',
            field=models.BooleanField(default=True, verbose_name='Действует'),
        ),
        migrations.AlterField(
            model_name='processes',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.Sections', verbose_name='Раздел'),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
