# Generated by Django 3.0 on 2020-01-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200108_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Ключ')),
                ('value', models.CharField(blank=True, max_length=100, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Настройка по умолчанию',
                'verbose_name_plural': 'Настройки по умолчанию',
            },
        ),
    ]
