# Generated by Django 3.0 on 2020-01-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='key',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='published',
            field=models.DateTimeField(auto_now=True, verbose_name='Опубликовано'),
        ),
    ]
