# Generated by Django 3.0 on 2020-01-12 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200112_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='problem',
            field=models.ForeignKey(limit_choices_to={'relevant': True}, on_delete=django.db.models.deletion.PROTECT, to='main_app.Problems', verbose_name='Проблема'),
        ),
    ]
